name: 'Dhall Typecheck'
description: 'Typecheck all .dhall files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dhallVersion }}
inputs:
  dhallVersion:
    description: 'Version of dhall-haskell to use'
    required: false
    default: '1.30.0'
